# -*- coding: utf-8 -*-
"""Logistic_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YDfNMRu3G0AkhecO7geqYLTiXJ3wSV-7
"""

import numpy as np

x=np.array([0.5,1.0,1.5,2.0,2.5,3.0,3.5,4.0,4.5,5.0])
y=np.array([0,0,0,0,1,0,1,1,1,1])

x

def sigmoid(z):
  return 1/(1+np.exp(-z))

def logistic_regression(x,y,lr = 0.1 , epochs =1000):
  w =0.0
  b =0.0
  n =len(x)
  for epoch in range(epochs):
    z = w*x+b
    predictions = sigmoid(z)
    dw = (1/n) * np.sum((predictions - y) * x)
    db = (1/n) * np.sum(predictions - y)

    w -=lr*dw
    b -=lr*db

    if epoch%200 ==0:
      loss = -np.mean(y*np.log(predictions + 1e-8) + (1-y) * np.log(1-predictions + 1e-8))

      print(f"Epoch {epoch}:Loss = {loss:.4f} , w = {w:.4f},b = {b:.4f}")
  return w,b

w, b = logistic_regression(x, y)
print(f"Final parameters: w = {w:.4f}, b = {b:.4f}")

test_hours = np.array([2.0,3.5,5.0])

for h in test_hours:
  prob = sigmoid(w*h+b)
  prediction = 1 if prob>0.5 else 0

  print(f"{h} hours study -> Probability of pass : {prob:.2f} ->{'Pass' if prediction==1 else 'Fail'}")